src/Worldsys.LDI.Web.Mvc/Areas/AppName/Controllers/WebhookSubscriptionController.cs
using System;
using System.Threading.Tasks;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Webhooks;
using Microsoft.AspNetCore.Mvc;
using Worldsys.LDI.Authorization;
using Worldsys.LDI.Web.Areas.AppName.Models.Webhooks;
using Worldsys.LDI.Web.Controllers;
using Worldsys.LDI.WebHooks;

namespace Worldsys.LDI.Web.Areas.AppName.Controllers
{
    [Area("AppName")]
    [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription)]
    public class WebhookSubscriptionController : LDIControllerBase
    {
        private readonly IWebhookSubscriptionAppService _webhookSubscriptionAppService;
        private readonly IWebhookEventAppService _webhookEventAppService;

        public WebhookSubscriptionController(
            IWebhookSubscriptionAppService webhookSubscriptionAppService,
            IWebhookEventAppService webhookEventAppService
            )
        {
            _webhookSubscriptionAppService = webhookSubscriptionAppService;
            _webhookEventAppService = webhookEventAppService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Edit)]
        public async Task<IActionResult> EditModal(string subscriptionId)
        {
            if (string.IsNullOrWhiteSpace(subscriptionId))
            {
                throw new ArgumentException(nameof(subscriptionId));
            }

            var availableWebhooks = await _webhookSubscriptionAppService.GetAllAvailableWebhooks();
            var model = new CreateOrEditWebhookSubscriptionViewModel()
            {
                WebhookSubscription = await _webhookSubscriptionAppService.GetSubscription(subscriptionId),
                AvailableWebhookEvents = availableWebhooks
            };

            return PartialView("_CreateOrEditModal", model);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Create)]
        public async Task<IActionResult> CreateModal()
        {
            var availableWebhooks = await _webhookSubscriptionAppService.GetAllAvailableWebhooks();
            var model = new CreateOrEditWebhookSubscriptionViewModel()
            {
                WebhookSubscription = new WebhookSubscription(),
                AvailableWebhookEvents = availableWebhooks
            };

            return PartialView("_CreateOrEditModal", model);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Detail)]
        public async Task<IActionResult> Detail(string id)
        {
            var subscription = await _webhookSubscriptionAppService.GetSubscription(id);

            return View(subscription);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_WebhookSubscription_Create)]
        public async Task<IActionResult> WebHookEventDetail(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                throw new ArgumentException(nameof(id));
            }

            var webhookEvent = await _webhookEventAppService.Get(id);
            return View(webhookEvent);
        }
    }
}

src/Worldsys.LDI.Web.Mvc/Areas/AppName/Views/WebhookSubscription/Detail.cshtml
@using Worldsys.LDI.Authorization
@using Worldsys.LDI.Web.TagHelpers
@model Abp.Webhooks.WebhookSubscription

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/WebhookSubscriptions/Detail.css" asp-append-version="true"/>
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/Common/_KeyValueListManager.css" asp-append-version="true"/>

}

@section Scripts
{
    <script>
        var subscriptionData = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model, Newtonsoft.Json.Formatting.Indented));
    </script>
    <script abp-src="/view-resources/Areas/AppName/Views/_Bundles/webhook-subscription-detail.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Areas/AppName/Views/Common/_KeyValueListManager.js" asp-append-version="true"></script>

}

@{
    var breadcrumbs = new List<BreadcrumbItem>()
    {
        new BreadcrumbItem(Url.Action("Index", "WebhookSubscription", new {Area = "AppName"}), @L("WebhookSubscriptions")),
        new BreadcrumbItem(L("WebhookSubscriptionDetail")),
    };
}

<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <abp-page-subheader title="@L("WebhookSubscriptionDetail")" breadcrumbs="breadcrumbs">
        @if (Model.IsActive)
        {
            <span class="label label-success label-inline">@L("Active")</span>
        }
        else
        {
            <span class="label label-dark label-inline">@L("Disabled")</span>
        }

        @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Edit) ||
             IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_ChangeActivity))
        {
            <div class="dropdown dropdown-inline ml-2">
                <a href="#" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="flaticon-more-1"></i>
                </a>
                <div class="dropdown-menu p-0 m-0 dropdown-menu-md dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-211px, 39px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <!--begin::Naviigation-->
                    <ul class="navi">
                        @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Edit))
                        {
                            <li class="navi-item">
                                <a href="javascript:;" id="subscription-edit-btn" class="navi-link">
                                    <span class="navi-text">@L("EditWebhookSubscription")</span>
                                </a>
                            </li>
                        }

                        @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_ChangeActivity))
                        {
                            <li class="navi-item">
                                <a href="javascript:;" id="activity-toggle-btn" class="navi-link">

                                    @if (Model.IsActive)
                                    {
                                        <span class="navi-text">@L("Disable")</span>
                                    }
                                    else
                                    {
                                        <span class="navi-text">@L("Enable")</span>
                                    }
                                </a>
                            </li>
                        }
                    </ul>
                    <!--end::Naviigation-->
                </div>
            </div>
        }
    </abp-page-subheader>

    <div class="@(await GetContainerClass())">
        <div class="card card-custom gutter-b" id="portlet-detail">
                       <div class="card-body">
                           <div class="form-group row">
                               <label class="col-2 col-form-label">@L("WebhookEndpoint")</label>
                               <div class="col-10 text-break">
                                   @Model.WebhookUri
                               </div>
                           </div>
                           <div class="form-group row">
                               <label class="col-2 col-form-label">@L("WebhookEvents")</label>
                               <div class="col-10 text-break">
                                   @if (Model.Webhooks != null)
                                   {
                                       @foreach (var webhookEvent in Model.Webhooks)
                                       {
                                           @webhookEvent
                                           <br/>
                                       }
                                   }
                               </div>
                           </div>
       
                           <div class="form-group row">
                               <label class="col-2 col-form-label">@L("AdditionalWebhookHeaders")</label>
                               <div class="col-10 text-break">
                                   @if (Model.Headers != null)
                                   {
                                       @foreach (var webhookHeader in Model.Headers)
                                       {
                                           @webhookHeader
                                           <br/>
                                       }
                                   }
                               </div>
                           </div>
       
                           <div class="form-group row mb-0">
                               <label class="col-2 col-form-label">@L("WebhookSecret")</label>
                               <div class="col-10 position-relative">
                                   <span class="blur" id="secretSpan">@Model.Secret</span>
                                   <div class="btn btn-sm btn-dark btn-elevate btn-elevate-air" id="secret-view-btn">@L("ViewWebhookSecret")</div>
                               </div>
                           </div>
                       </div>
                   </div>
                   <div class="card card-custom gutter-b">
                       <div class="card-header align-items-center border-0 mt-4">
                           <h3 class="card-title align-items-start flex-column">
                               <span class="font-weight-bolder text-dark">@L("WebhookSendAttempts")</span>
                           </h3>
                           <div class="card-toolbar">
                               <button id="refresh-send-attempts-btn" class="btn btn-outline-brand btn-sm btn-icon btn-icon-md">
                                   <i class="flaticon2-refresh"></i>
                               </button>
                           </div>
                       </div>
       
                       <div class="card-body">
                           <div class="align-items-center">
                               <table id="WebHookSendAttemptTable" class="display table table-separate table-head-custom no-footer dtr-inline dt-responsive nowrap">
                                   <thead>
                                   <tr>
                                       <th></th>
                                       <th style="text-align: center;width: 60px">@L("Actions")</th>
                                       <th>@L("WebhookEvent")</th>
                                       <th>@L("WebhookEventId")</th>
                                       <th>@L("CreationTime")</th>
                                       <th>@L("HttpStatusCode")</th>
                                       <th>@L("Response")</th>
                                       <th>@L("Data")</th>
                                   </tr>
                                   </thead>
                               </table>
                           </div>
                       </div>
                   </div>
    </div>
</div>
<div class="modal fade" id="SendAttemptDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

src/Worldsys.LDI.Web.Mvc/Areas/AppName/Views/WebhookSubscription/Index.cshtml
@using Worldsys.LDI.Authorization
@using Worldsys.LDI.Web.Areas.AppName.Startup
@{
    ViewBag.CurrentPageName = AppNamePageNames.Common.WebhookSubscriptions;
}

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/WebhookSubscriptions/Index.css" asp-append-version="true"/>
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/Common/_KeyValueListManager.css" asp-append-version="true"/>
}

@section Scripts
{
    <script abp-src="/view-resources/Areas/AppName/Views/_Bundles/webhook-subscription-list.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Areas/AppName/Views/Common/_KeyValueListManager.js" asp-append-version="true"></script>
}

<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <abp-page-subheader title="@L("WebhookSubscriptions")" description="@L("WebhookSubscriptionsInfo")">
        @if (IsGranted(AppPermissions.Pages_Administration_WebhookSubscription_Create))
        {
            <button id="CreateNewWebhookSubscription" class="btn btn-primary">
                <i class="fa fa-plus"></i> @L("AddNewWebhookSubscription")
            </button>
        }
    </abp-page-subheader>

    <div class="@(await GetContainerClass())">
        <div class="card card-custom gutter-b">
                        <div class="card-body">
                            <div class="align-items-center">
                                <table id="SubscriptionTable" class="display table table-separate no-footer dtr-inline dt-responsive nowrap">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th style="width:100px;"></th>
                                        <th>@L("WebhookEndpoint")</th>
                                        <th>@L("WebhookEvents")</th>
                                        <th>@L("IsActive")</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
    </div>
</div>

src/Worldsys.LDI.Web.Mvc/Areas/AppName/Views/WebhookSubscription/WebHookEventDetail.cshtml
@using Worldsys.LDI.Authorization
@model Abp.Webhooks.WebhookEvent

@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/WebhookSubscriptions/Detail.css" asp-append-version="true"/>
}

@section Scripts
{
    <script>
        var webhookEventId = "@Html.Raw(Model.Id)";
    </script>
    <script abp-src="/view-resources/Areas/AppName/Views/_Bundles/webhook-event-detail.js" asp-append-version="true"></script>
}

@{
    int maxDataLength = 300;
}
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <abp-page-subheader title="@L("WebhookEventDetail")"></abp-page-subheader>
    <div class="@(await GetContainerClass()) d-flex flex-column-fluid">
        <div class="container">
            <div class="card card-custom gutter-b" id="portlet-detail">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-2 col-form-label">@L("WebhookEvent")</label>
                        <div class="col-10">
                            @Model.WebhookName
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 col-form-label">@L("CreationTime")</label>
                        <div class="col-10">
                            @Model.CreationTime
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">@L("Data")</label>
                        <div class="col-10 text-break">
                            @if (Model.Data.Length <= maxDataLength)
                            {
                                @Model.Data
                            }
                            else
                            {
                                <p>
                                    <span id="dataDots">@Model.Data.Substring(0, maxDataLength). . .</span>
                                    <span id="dataMore" class="d-none">@Model.Data</span>
                                </p>
                                <button class="btn btn-outline-primary btn-sm" id="dataShowMoreBtn">@L("ShowData")</button>
                            }
                        </div>
                    </div>
                </div>
            </div>

            <div class="card card-custom gutter-b">
                <div class="card-header align-items-center border-0 mt-4">
                    <h3 class="card-title align-items-start flex-column">
                        <span class="font-weight-bolder text-dark">@L("WebhookSendAttempts")</span>
                    </h3>
                    <div class="card-toolbar">
                        <button id="refresh-send-attempts-btn" class="btn btn-outline-brand btn-sm btn-icon btn-icon-md">
                            <i class="flaticon2-refresh"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="align-items-center">
                        <table id="WebhookEventDetailSendAttemptsTable" class="display table table-separate table-head-custom no-footer dtr-inline dt-responsive nowrap">
                            <thead>
                            <tr>
                                <th style="width: 10px"></th>
                                <th style="width: 60px;text-align: center">@L("Actions")</th>
                                <th style="width: 60px;text-align: center">@L("WebhookSubscriptionId")</th>
                                <th style="text-align: center">@L("WebhookEndpoint")</th>
                                <th style="width: 60px;">@L("CreationTime")</th>
                                <th style="width: 120px;">@L("HttpStatusCode")</th>
                                <th>@L("Response")</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="SendAttemptDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

src/Worldsys.LDI.Web.Mvc/Areas/AppName/Views/WebhookSubscription/_CreateOrEditModal.cshtml
@using Worldsys.LDI.Web.Areas.AppName.Models.Common.Modals
@model Worldsys.LDI.Web.Areas.AppName.Models.Webhooks.CreateOrEditWebhookSubscriptionViewModel

<script>
    var createOrEditIsEdit = @Html.Raw(Model.WebhookSubscription.Id==default?"false":"true");
    var createOrEditHeaders = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.WebhookSubscription.Headers, Newtonsoft.Json.Formatting.Indented));
</script>
<link rel="stylesheet" abp-href="/view-resources/Areas/AppName/Views/WebhookSubscriptions/_CreateOrEditModal.css" asp-append-version="true" />

@await Html.PartialAsync("~/Areas/AppName/Views/Common/Modals/_ModalHeader.cshtml",
    new ModalHeaderViewModel(Model.WebhookSubscription.Id == default ? L("AddNewWebhookSubscription") : L("EditWebhookSubscription")))

<div class="modal-body">
    @if (Model.WebhookSubscription.Id != default)
    {
        <input type="hidden" name="Id" value="@Model.WebhookSubscription.Id" />
    }

    <div class="form-group col-12">
        <label for="webhookUri">@L("WebhookEndpoint")</label>
        <input id="webhookEndpointURL" type="text" name="webhookUri" class="form-control" value="@Model.WebhookSubscription.WebhookUri">
    </div>

    <div class="form-group col-12">
        <label for="webhookUri">@L("WebhookEvents")</label>
        @Html.DropDownList(
            "Webhooks",
            Model.AvailableWebhookEvents.Items.Select(e => new SelectListItem(e.Name, e.Description, Model.WebhookSubscription.Webhooks.Contains(e.Name)))
            , new { @class = "form-control select2 col-12", multiple = "multiple", style = "width: 100%;" }
            )
    </div>

    <hr />
    <div class="form-group col-12">
        <label for="webhookUri">@L("AdditionalWebhookHeaders")</label>
        <div id="additional-header-list">
           
        </div>
    </div>
</div>

@await Html.PartialAsync("~/Areas/AppName/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")